### PR TITLE
provide a textarea for pasting a custom file

### LINKED ISSUE #9: As editor for json and other formats
To make this more than a slightly crippled demo for nushell, we could offer a textarea (and upload/dnd section) for providing JSON, toml, csv or other data that nushell can parse (maybe auto detect the format), then a pipeline for processing it and an output area for the result, as HTML table and whatever structured output is desired (default to input format, can switch to something else.

The format selects could be fed with a list of subcommands from "from" and "to".

Since everything runs on the client, we could update everything automatically while typing, as long as the pipeline is a valid command

### PR DESCRIPTION
**Pull request by jzaefferer**
currently the ZipFS conflicts with this; with only the LocalStorage fs it works

Fixes #9

### CODE REVIEW

**Comment by jonathandturner** [comment]
@jzaefferer - Yeah, I wondered about the zip limitation to not be writeable. I think it's fine to remove, since ultimately we'd like them to be able to use `save` also. Do you know if there's another way we could fill in some default files into the in-memory one? I guess we could load them ourselves.

**Comment by jzaefferer** [comment]
Updated! This is now ready for a review.

**Comment by jzaefferer** [comment]
Preview:

Screenshot 2020-08-01 at 12 15 18

**Comment by fdncred** [comment]
very cool @jzaefferer !!!

**Pull request merged**
